start-at-login = true

after-login-command = []
after-startup-command = []

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = 'move-mouse window-lazy-center'

[gaps]
inner.horizontal = 4
inner.vertical = 4
outer.left = 8
outer.bottom = 8
outer.right = 8
outer.top = 8

[mode.main.binding]
alt-shift-slash = 'layout tiles horizontal vertical'
alt-shift-comma = 'layout accordion horizontal vertical'

alt-a = 'focus left'
alt-s = 'focus right'
alt-w = 'focus up'
alt-d = 'focus right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-shift-f = 'fullscreen'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-b = 'workspace B'
alt-o = 'workspace O'
alt-t = 'workspace T'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-b = 'move-node-to-workspace B' # for browser(s)
alt-shift-o = 'move-node-to-workspace O'
alt-shift-t = 'move-node-to-workspace T' # for terminal

alt-shift-tab = 'workspace-back-and-forth'
alt-ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-a = ['join-with left', 'mode main']
alt-s = ['join-with down', 'mode main']
alt-w = ['join-with up', 'mode main']
alt-d = ['join-with right', 'mode main']


