[font]
normal = { family = "FiraCode Nerd Font Propo", style = "Retina" }
bold = { family = "FiraCode Nerd Font Propo", style = "Bold" }
italic = { family = "FiraCode Nerd Font Propo", style = "Italic" }
size = 18
